name: Test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Run nightly at 2 AM UTC to catch provider drift
    - cron: '0 2 * * *'

jobs:
  test:
    name: Terraform ${{ matrix.terraform_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        terraform_version: ['1.5.7', '1.7.5', '1.9.8', '1.11.4', '1.13.4', 'latest']
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform_version }}
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init

      - name: Run all tests
        run: |
          chmod +x test-all-versions.sh
          ./test-all-versions.sh

      - name: Clean up test artifacts
        if: always()
        run: |
          rm -rf tests/provider_versions/*/terraform.tfstate*
          rm -rf tests/provider_versions/*/.terraform
          rm -rf tests/provider_versions/*/.terraform.lock.hcl
